package chenwei.tool_set.protobuf;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmailProto.proto

public final class EmailProto {
  private EmailProto() {
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttachmentOrBuilder
      extends
        // @@protoc_insertion_point(interface_extends:Attachment)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>string originalFilename = 2;</code>
     */
    java.lang.String getOriginalFilename();
    /**
     * <code>string originalFilename = 2;</code>
     */
    com.google.protobuf.ByteString getOriginalFilenameBytes();

    /**
     * <code>string contentType = 3;</code>
     */
    java.lang.String getContentType();
    /**
     * <code>string contentType = 3;</code>
     */
    com.google.protobuf.ByteString getContentTypeBytes();

    /**
     * <code>bytes content = 4;</code>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code Attachment}
   */
  public static final class Attachment
      extends
        com.google.protobuf.GeneratedMessageV3
      implements
        // @@protoc_insertion_point(message_implements:Attachment)
        AttachmentOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Attachment.newBuilder() to construct.
    private Attachment(
        com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Attachment() {
      name_ = "";
      originalFilename_ = "";
      contentType_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }
    private Attachment(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
          .newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0 :
              done = true;
              break;
            default : {
              if (!parseUnknownFieldProto3(input, unknownFields,
                  extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10 : {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18 : {
              java.lang.String s = input.readStringRequireUtf8();

              originalFilename_ = s;
              break;
            }
            case 26 : {
              java.lang.String s = input.readStringRequireUtf8();

              contentType_ = s;
              break;
            }
            case 34 : {

              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return EmailProto.internal_static_Attachment_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return EmailProto.internal_static_Attachment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(EmailProto.Attachment.class,
              EmailProto.Attachment.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    @Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGINALFILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object originalFilename_;
    /**
     * <code>string originalFilename = 2;</code>
     */
    @Override
    public java.lang.String getOriginalFilename() {
      java.lang.Object ref = originalFilename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalFilename_ = s;
        return s;
      }
    }
    /**
     * <code>string originalFilename = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getOriginalFilenameBytes() {
      java.lang.Object ref = originalFilename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        originalFilename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENTTYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object contentType_;
    /**
     * <code>string contentType = 3;</code>
     */
    @Override
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      }
    }
    /**
     * <code>string contentType = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getOriginalFilenameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2,
            originalFilename_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3,
            contentType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1,
            name_);
      }
      if (!getOriginalFilenameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2,
            originalFilename_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3,
            contentType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream.computeBytesSize(4,
            content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof EmailProto.Attachment)) {
        return super.equals(obj);
      }
      EmailProto.Attachment other = (EmailProto.Attachment) obj;

      boolean result = true;
      result = result && getName().equals(other.getName());
      result = result
          && getOriginalFilename().equals(other.getOriginalFilename());
      result = result && getContentType().equals(other.getContentType());
      result = result && getContent().equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ORIGINALFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalFilename().hashCode();
      hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmailProto.Attachment parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Attachment parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Attachment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Attachment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Attachment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Attachment parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Attachment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input);
    }
    public static EmailProto.Attachment parseFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input, extensionRegistry);
    }
    public static EmailProto.Attachment parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmailProto.Attachment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmailProto.Attachment parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input);
    }
    public static EmailProto.Attachment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmailProto.Attachment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder()
          : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Attachment}
     */
    public static final class Builder
        extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
          // @@protoc_insertion_point(builder_implements:Attachment)
          EmailProto.AttachmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return EmailProto.internal_static_Attachment_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return EmailProto.internal_static_Attachment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(EmailProto.Attachment.class,
                EmailProto.Attachment.Builder.class);
      }

      // Construct using EmailProto.Attachment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        name_ = "";

        originalFilename_ = "";

        contentType_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return EmailProto.internal_static_Attachment_descriptor;
      }

      @Override
      public EmailProto.Attachment getDefaultInstanceForType() {
        return EmailProto.Attachment.getDefaultInstance();
      }

      @Override
      public EmailProto.Attachment build() {
        EmailProto.Attachment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EmailProto.Attachment buildPartial() {
        EmailProto.Attachment result = new EmailProto.Attachment(this);
        result.name_ = name_;
        result.originalFilename_ = originalFilename_;
        result.contentType_ = contentType_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmailProto.Attachment) {
          return mergeFrom((EmailProto.Attachment) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmailProto.Attachment other) {
        if (other == EmailProto.Attachment.getDefaultInstance())
          return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getOriginalFilename().isEmpty()) {
          originalFilename_ = other.originalFilename_;
          onChanged();
        }
        if (!other.getContentType().isEmpty()) {
          contentType_ = other.contentType_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmailProto.Attachment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmailProto.Attachment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      @Override
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object originalFilename_ = "";
      /**
       * <code>string originalFilename = 2;</code>
       */
      @Override
      public java.lang.String getOriginalFilename() {
        java.lang.Object ref = originalFilename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originalFilename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string originalFilename = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getOriginalFilenameBytes() {
        java.lang.Object ref = originalFilename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          originalFilename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string originalFilename = 2;</code>
       */
      public Builder setOriginalFilename(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        originalFilename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string originalFilename = 2;</code>
       */
      public Builder clearOriginalFilename() {

        originalFilename_ = getDefaultInstance().getOriginalFilename();
        onChanged();
        return this;
      }
      /**
       * <code>string originalFilename = 2;</code>
       */
      public Builder setOriginalFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        originalFilename_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentType_ = "";
      /**
       * <code>string contentType = 3;</code>
       */
      @Override
      public java.lang.String getContentType() {
        java.lang.Object ref = contentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contentType = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getContentTypeBytes() {
        java.lang.Object ref = contentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          contentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contentType = 3;</code>
       */
      public Builder setContentType(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contentType = 3;</code>
       */
      public Builder clearContentType() {

        contentType_ = getDefaultInstance().getContentType();
        onChanged();
        return this;
      }
      /**
       * <code>string contentType = 3;</code>
       */
      public Builder setContentTypeBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        contentType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:Attachment)
    }

    // @@protoc_insertion_point(class_scope:Attachment)
    private static final EmailProto.Attachment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmailProto.Attachment();
    }

    public static EmailProto.Attachment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Attachment> PARSER = new com.google.protobuf.AbstractParser<Attachment>() {
      @Override
      public Attachment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Attachment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Attachment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Attachment> getParserForType() {
      return PARSER;
    }

    @Override
    public EmailProto.Attachment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MailOrBuilder
      extends
        // @@protoc_insertion_point(interface_extends:Mail)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
     * </pre>
     *
     * <code>string subject = 1;</code>
     */
    java.lang.String getSubject();
    /**
     * <pre>
     * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
     * </pre>
     *
     * <code>string subject = 1;</code>
     */
    com.google.protobuf.ByteString getSubjectBytes();

    /**
     * <code>string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>string body = 2;</code>
     */
    com.google.protobuf.ByteString getBodyBytes();

    /**
     * <code>string to = 3;</code>
     */
    java.lang.String getTo();
    /**
     * <code>string to = 3;</code>
     */
    com.google.protobuf.ByteString getToBytes();

    /**
     * <code>string cc = 4;</code>
     */
    java.lang.String getCc();
    /**
     * <code>string cc = 4;</code>
     */
    com.google.protobuf.ByteString getCcBytes();

    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    java.util.List<EmailProto.Attachment> getAttachmentsList();
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    EmailProto.Attachment getAttachments(int index);
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    int getAttachmentsCount();
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    java.util.List<? extends EmailProto.AttachmentOrBuilder> getAttachmentsOrBuilderList();
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    EmailProto.AttachmentOrBuilder getAttachmentsOrBuilder(int index);
  }
  /**
   * Protobuf type {@code Mail}
   */
  public static final class Mail extends com.google.protobuf.GeneratedMessageV3
      implements
        // @@protoc_insertion_point(message_implements:Mail)
        MailOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Mail.newBuilder() to construct.
    private Mail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Mail() {
      subject_ = "";
      body_ = "";
      to_ = "";
      cc_ = "";
      attachments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }
    private Mail(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
          .newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0 :
              done = true;
              break;
            default : {
              if (!parseUnknownFieldProto3(input, unknownFields,
                  extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10 : {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
            case 18 : {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            case 26 : {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 34 : {
              java.lang.String s = input.readStringRequireUtf8();

              cc_ = s;
              break;
            }
            case 42 : {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                attachments_ = new java.util.ArrayList<EmailProto.Attachment>();
                mutable_bitField0_ |= 0x00000010;
              }
              attachments_.add(input.readMessage(EmailProto.Attachment.parser(),
                  extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          attachments_ = java.util.Collections.unmodifiableList(attachments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return EmailProto.internal_static_Mail_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return EmailProto.internal_static_Mail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(EmailProto.Mail.class,
              EmailProto.Mail.Builder.class);
    }

    private int bitField0_;
    public static final int SUBJECT_FIELD_NUMBER = 1;
    private volatile java.lang.Object subject_;
    /**
     * <pre>
     * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
     * </pre>
     *
     * <code>string subject = 1;</code>
     */
    @Override
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
     * </pre>
     *
     * <code>string subject = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 2;</code>
     */
    @Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <code>string to = 3;</code>
     */
    @Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>string to = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CC_FIELD_NUMBER = 4;
    private volatile java.lang.Object cc_;
    /**
     * <code>string cc = 4;</code>
     */
    @Override
    public java.lang.String getCc() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cc_ = s;
        return s;
      }
    }
    /**
     * <code>string cc = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getCcBytes() {
      java.lang.Object ref = cc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
            .copyFromUtf8((java.lang.String) ref);
        cc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACHMENTS_FIELD_NUMBER = 5;
    private java.util.List<EmailProto.Attachment> attachments_;
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    @Override
    public java.util.List<EmailProto.Attachment> getAttachmentsList() {
      return attachments_;
    }
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    @Override
    public java.util.List<? extends EmailProto.AttachmentOrBuilder> getAttachmentsOrBuilderList() {
      return attachments_;
    }
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    @Override
    public int getAttachmentsCount() {
      return attachments_.size();
    }
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    @Override
    public EmailProto.Attachment getAttachments(int index) {
      return attachments_.get(index);
    }
    /**
     * <code>repeated .Attachment attachments = 5;</code>
     */
    @Override
    public EmailProto.AttachmentOrBuilder getAttachmentsOrBuilder(int index) {
      return attachments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!getSubjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subject_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (!getCcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cc_);
      }
      for (int i = 0; i < attachments_.size(); i++) {
        output.writeMessage(5, attachments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!getSubjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1,
            subject_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2,
            body_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3,
            to_);
      }
      if (!getCcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4,
            cc_);
      }
      for (int i = 0; i < attachments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(5,
            attachments_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof EmailProto.Mail)) {
        return super.equals(obj);
      }
      EmailProto.Mail other = (EmailProto.Mail) obj;

      boolean result = true;
      result = result && getSubject().equals(other.getSubject());
      result = result && getBody().equals(other.getBody());
      result = result && getTo().equals(other.getTo());
      result = result && getCc().equals(other.getCc());
      result = result
          && getAttachmentsList().equals(other.getAttachmentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + getCc().hashCode();
      if (getAttachmentsCount() > 0) {
        hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAttachmentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmailProto.Mail parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Mail parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Mail parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Mail parseFrom(com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Mail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmailProto.Mail parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmailProto.Mail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input);
    }
    public static EmailProto.Mail parseFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input, extensionRegistry);
    }
    public static EmailProto.Mail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EmailProto.Mail parseDelimitedFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmailProto.Mail parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input);
    }
    public static EmailProto.Mail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER,
          input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
      return newBuilder();
    }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmailProto.Mail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder()
          : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Mail}
     */
    public static final class Builder
        extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
          // @@protoc_insertion_point(builder_implements:Mail)
          EmailProto.MailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return EmailProto.internal_static_Mail_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return EmailProto.internal_static_Mail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(EmailProto.Mail.class,
                EmailProto.Mail.Builder.class);
      }

      // Construct using EmailProto.Mail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getAttachmentsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        subject_ = "";

        body_ = "";

        to_ = "";

        cc_ = "";

        if (attachmentsBuilder_ == null) {
          attachments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          attachmentsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return EmailProto.internal_static_Mail_descriptor;
      }

      @Override
      public EmailProto.Mail getDefaultInstanceForType() {
        return EmailProto.Mail.getDefaultInstance();
      }

      @Override
      public EmailProto.Mail build() {
        EmailProto.Mail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EmailProto.Mail buildPartial() {
        EmailProto.Mail result = new EmailProto.Mail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.subject_ = subject_;
        result.body_ = body_;
        result.to_ = to_;
        result.cc_ = cc_;
        if (attachmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            attachments_ = java.util.Collections.unmodifiableList(attachments_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.attachments_ = attachments_;
        } else {
          result.attachments_ = attachmentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmailProto.Mail) {
          return mergeFrom((EmailProto.Mail) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmailProto.Mail other) {
        if (other == EmailProto.Mail.getDefaultInstance())
          return this;
        if (!other.getSubject().isEmpty()) {
          subject_ = other.subject_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getCc().isEmpty()) {
          cc_ = other.cc_;
          onChanged();
        }
        if (attachmentsBuilder_ == null) {
          if (!other.attachments_.isEmpty()) {
            if (attachments_.isEmpty()) {
              attachments_ = other.attachments_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAttachmentsIsMutable();
              attachments_.addAll(other.attachments_);
            }
            onChanged();
          }
        } else {
          if (!other.attachments_.isEmpty()) {
            if (attachmentsBuilder_.isEmpty()) {
              attachmentsBuilder_.dispose();
              attachmentsBuilder_ = null;
              attachments_ = other.attachments_;
              bitField0_ = (bitField0_ & ~0x00000010);
              attachmentsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                  ? getAttachmentsFieldBuilder()
                  : null;
            } else {
              attachmentsBuilder_.addAllMessages(other.attachments_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EmailProto.Mail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EmailProto.Mail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object subject_ = "";
      /**
       * <pre>
       * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
       * </pre>
       *
       * <code>string subject = 1;</code>
       */
      @Override
      public java.lang.String getSubject() {
        java.lang.Object ref = subject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
       * </pre>
       *
       * <code>string subject = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getSubjectBytes() {
        java.lang.Object ref = subject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          subject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
       * </pre>
       *
       * <code>string subject = 1;</code>
       */
      public Builder setSubject(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
       * </pre>
       *
       * <code>string subject = 1;</code>
       */
      public Builder clearSubject() {

        subject_ = getDefaultInstance().getSubject();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 定义Mail的成员变量，需要指定：变量类型、变量名、变量Tag
       * </pre>
       *
       * <code>string subject = 1;</code>
       */
      public Builder setSubjectBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        subject_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 2;</code>
       */
      @Override
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBody(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder clearBody() {

        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 2;</code>
       */
      public Builder setBodyBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        body_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>string to = 3;</code>
       */
      @Override
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to = 3;</code>
       */
      public Builder setTo(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to = 3;</code>
       */
      public Builder clearTo() {

        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>string to = 3;</code>
       */
      public Builder setToBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cc_ = "";
      /**
       * <code>string cc = 4;</code>
       */
      @Override
      public java.lang.String getCc() {
        java.lang.Object ref = cc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cc = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getCcBytes() {
        java.lang.Object ref = cc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString
              .copyFromUtf8((java.lang.String) ref);
          cc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cc = 4;</code>
       */
      public Builder setCc(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 4;</code>
       */
      public Builder clearCc() {

        cc_ = getDefaultInstance().getCc();
        onChanged();
        return this;
      }
      /**
       * <code>string cc = 4;</code>
       */
      public Builder setCcBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        cc_ = value;
        onChanged();
        return this;
      }

      private java.util.List<EmailProto.Attachment> attachments_ = java.util.Collections
          .emptyList();
      private void ensureAttachmentsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          attachments_ = new java.util.ArrayList<EmailProto.Attachment>(
              attachments_);
          bitField0_ |= 0x00000010;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<EmailProto.Attachment, EmailProto.Attachment.Builder, EmailProto.AttachmentOrBuilder> attachmentsBuilder_;

      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      @Override
      public java.util.List<EmailProto.Attachment> getAttachmentsList() {
        if (attachmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attachments_);
        } else {
          return attachmentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      @Override
      public int getAttachmentsCount() {
        if (attachmentsBuilder_ == null) {
          return attachments_.size();
        } else {
          return attachmentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      @Override
      public EmailProto.Attachment getAttachments(int index) {
        if (attachmentsBuilder_ == null) {
          return attachments_.get(index);
        } else {
          return attachmentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder setAttachments(int index, EmailProto.Attachment value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.set(index, value);
          onChanged();
        } else {
          attachmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder setAttachments(int index,
          EmailProto.Attachment.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.set(index, builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder addAttachments(EmailProto.Attachment value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.add(value);
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder addAttachments(int index, EmailProto.Attachment value) {
        if (attachmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttachmentsIsMutable();
          attachments_.add(index, value);
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder addAttachments(
          EmailProto.Attachment.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.add(builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder addAttachments(int index,
          EmailProto.Attachment.Builder builderForValue) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.add(index, builderForValue.build());
          onChanged();
        } else {
          attachmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder addAllAttachments(
          java.lang.Iterable<? extends EmailProto.Attachment> values) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values,
              attachments_);
          onChanged();
        } else {
          attachmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder clearAttachments() {
        if (attachmentsBuilder_ == null) {
          attachments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          attachmentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public Builder removeAttachments(int index) {
        if (attachmentsBuilder_ == null) {
          ensureAttachmentsIsMutable();
          attachments_.remove(index);
          onChanged();
        } else {
          attachmentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public EmailProto.Attachment.Builder getAttachmentsBuilder(int index) {
        return getAttachmentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      @Override
      public EmailProto.AttachmentOrBuilder getAttachmentsOrBuilder(int index) {
        if (attachmentsBuilder_ == null) {
          return attachments_.get(index);
        } else {
          return attachmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      @Override
      public java.util.List<? extends EmailProto.AttachmentOrBuilder> getAttachmentsOrBuilderList() {
        if (attachmentsBuilder_ != null) {
          return attachmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attachments_);
        }
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public EmailProto.Attachment.Builder addAttachmentsBuilder() {
        return getAttachmentsFieldBuilder()
            .addBuilder(EmailProto.Attachment.getDefaultInstance());
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public EmailProto.Attachment.Builder addAttachmentsBuilder(int index) {
        return getAttachmentsFieldBuilder().addBuilder(index,
            EmailProto.Attachment.getDefaultInstance());
      }
      /**
       * <code>repeated .Attachment attachments = 5;</code>
       */
      public java.util.List<EmailProto.Attachment.Builder> getAttachmentsBuilderList() {
        return getAttachmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<EmailProto.Attachment, EmailProto.Attachment.Builder, EmailProto.AttachmentOrBuilder> getAttachmentsFieldBuilder() {
        if (attachmentsBuilder_ == null) {
          attachmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<EmailProto.Attachment, EmailProto.Attachment.Builder, EmailProto.AttachmentOrBuilder>(
              attachments_, ((bitField0_ & 0x00000010) == 0x00000010),
              getParentForChildren(), isClean());
          attachments_ = null;
        }
        return attachmentsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:Mail)
    }

    // @@protoc_insertion_point(class_scope:Mail)
    private static final EmailProto.Mail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmailProto.Mail();
    }

    public static EmailProto.Mail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mail> PARSER = new com.google.protobuf.AbstractParser<Mail>() {
      @Override
      public Mail parsePartialFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Mail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mail> getParserForType() {
      return PARSER;
    }

    @Override
    public EmailProto.Mail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_Attachment_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Attachment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_Mail_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Mail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\020EmailProto.proto\"Z\n\nAttachment\022\014\n\004name"
            + "\030\001 \001(\t\022\030\n\020originalFilename\030\002 \001(\t\022\023\n\013cont"
            + "entType\030\003 \001(\t\022\017\n\007content\030\004 \001(\014\"_\n\004Mail\022\017"
            + "\n\007subject\030\001 \001(\t\022\014\n\004body\030\002 \001(\t\022\n\n\002to\030\003 \001("
            + "\t\022\n\n\002cc\030\004 \001(\t\022 \n\013attachments\030\005 \003(\0132\013.Att"
            + "achmentb\006proto3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
      @Override
      public com.google.protobuf.ExtensionRegistry assignDescriptors(
          com.google.protobuf.Descriptors.FileDescriptor root) {
        descriptor = root;
        return null;
      }
    };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    internal_static_Attachment_descriptor = getDescriptor().getMessageTypes()
        .get(0);
    internal_static_Attachment_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Attachment_descriptor, new java.lang.String[]{"Name",
            "OriginalFilename", "ContentType", "Content",});
    internal_static_Mail_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_Mail_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Mail_descriptor,
        new java.lang.String[]{"Subject", "Body", "To", "Cc", "Attachments",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
